version: '3.8'

services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=wl_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"
    networks:
      - db-net

  web:
    restart: always
    command: gunicorn config.wsgi
      #gunicorn config.wsgi -b 0.0.0.0:8000
    # command : bash -c "python manage.py migrate &&
      #                 python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./src/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - db-net
    
  reactapp:
    restart: always
    command : bash -c "npm run build 
    # && npm start"
    build:
      context: .src/reactapp/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - web
    networks:
      - db-net

networks:
  db-net:
    driver: bridge