# Generated by Django 3.2.9 on 2021-12-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_set_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
