# Generated by Django 3.2.9 on 2021-12-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_rename_completed_set_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='title',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
