# Generated by Django 3.2.9 on 2021-12-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_workout_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='musclegroup',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
