# Generated by Django 3.2.9 on 2021-12-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='completed',
            field=models.BooleanField(null=True),
        ),
    ]
