# Generated by Django 3.2.9 on 2021-12-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_alter_set_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='completed',
            new_name='checked',
        ),
    ]
